define: DUK_USE_JSON_ENC_RECURSION_LIMIT
introduced: 1.3.0
default: 1000
tags:
  - portability
  - cstackdepth
description: >
  Maximum native stack recursion for JSON encoding.

  Must be higher than the internal DUK_JSON_ENC_LOOPARRAY define (current value 64).
