# Reduce recursion limits for shallow C stack targets.
# These values are based on the (removed) DUK_USE_DEEP_C_STACK option.

DUK_USE_CALL_RECURSION_LIMIT: 60
DUK_USE_COMPILER_RECURSION_LIMIT: 50
DUK_USE_RE_COMPILER_RECURSION_LIMIT: 100
DUK_USE_RE_EXECUTOR_RECURSION_LIMIT: 100
DUK_USE_JSON_ENC_RECURSION_LIMIT: 100
DUK_USE_JSON_DEC_RECURSION_LIMIT: 100
DUK_USE_MARK_AND_SWEEP_RECURSION_LIMIT: 32
